---
title: "EDA - Stat 3302 Project"
author: "Kyle Voytovich"
output: pdf_document
---

```{r, echo = FALSE}

wd <- "/Users/iowner/OneDrive/School/Spring_2016/Stat 3302/Project/Stat 3302 Project/"
setwd(wd)

bonds <- read.table("Bonds Data", header = TRUE)

```

```{r, echo = FALSE}

# count_successes: returns a data frame of the number of successes and
#   failures in the result divided by the values that variable takes
#     @result - 0/1 vector where 0 is a failure and 1 is a success
#     @variable - values to split successes and failures into
#     @name - name of variable in output data frame
count_successes <- function(result, variable, name) {
  success <- function(result) {
    return(sum(result == 1))
  }
  failure <- function(result) {
    return(sum(result == 0))
  }
  
  suc <- aggregate(list(result = result),
                   by = list(variable = variable),
                   FUN = success)
  
  fai <- aggregate(list(result = result),
                   by = list(variable = variable),
                   FUN = failure)
  
  res <- data.frame(variable = suc$variable,
                    success = suc$result,
                    failure = fai$result,
                    total = suc$result + fai$result)
  names(res) <- c(name, "success", "failure", "total")
  
  return(res)
}

# percent_successes:
percent_successes <- function(df) {
  result <- df
  result$success <- result$success / result$total
  result$failure <- result$failure / result$total
  return(result)
}

```

# Whether Bonds gets on base

```{r}

bonds$success <- as.numeric(bonds$result != 0)

bonds$onbase <- bonds$first + bonds$second + bonds$third
bonds$inningcap <- ifelse(bonds$inning >= 10, 10, bonds$inning)
bonds$appearancecap <- ifelse(bonds$appearance >= 5, 5, bonds$appearance)
bonds$erarange <- floor(bonds$era)

home <- count_successes(bonds$success, bonds$home, "home")
first <- count_successes(bonds$success, bonds$first, "first")
second <- count_successes(bonds$success, bonds$second, "second")
third <- count_successes(bonds$success, bonds$third, "third")
onbase <- count_successes(bonds$success, bonds$onbase, "onbase")
outs <- count_successes(bonds$success, bonds$outs, "outs")
inning <- count_successes(bonds$success, bonds$inningcap, "inningcap")
appearance <- count_successes(bonds$success, bonds$appearancecap, "appearancecap")
era <- count_successes(bonds$success, bonds$erarange, "erarange")

homep <- percent_successes(home)
firstp <- percent_successes(first)
secondp <- percent_successes(second)
thirdp <- percent_successes(third)
onbasep <- percent_successes(onbase)
outsp <- percent_successes(outs)
inningp <- percent_successes(inning)
appearancep <- percent_successes(appearance)
erap <- percent_successes(era)

```

## Is it a home game?

```{r, echo = FALSE}

home
round(homep, 2)

```

\pagebreak

# Is someone on first base?

```{r, echo = FALSE}

first
round(firstp, 2)

```

# Is someone on second base?

```{r, echo = FALSE}

second
round(secondp, 2)

```

# Is someone on third base?

```{r, echo = FALSE}

third
round(thirdp, 2)

```

# How many people are on base?

```{r, echo = FALSE}

onbase
round(onbasep, 2)

```

# How many outs are there?

```{r, echo = FALSE}

outs
round(outsp, 2)

```

# What inning is it?

```{r, echo = FALSE}

inning
round(inningp, 2)

```

\pagebreak

# What appearance is it for bonds?

```{r, echo = FALSE}

appearance
round(appearancep, 2)

```

# What's the opposing pitcher's era?

```{r, echo = FALSE}

era
round(erap, 2)

```




